---
- name: Устанавливаю cifs-utils
  ansible.builtin.package:
    name:
      - cifs-utils
      # - heimdal-clients
    state: present

- name: Удаляю старый ключ
  ansible.builtin.file:
    state: absent
    path: /etc/krb5-2.keytab

- name: Создаю новый ключ
  ansible.builtin.expect:
    command: ktutil
    responses:
      ktutil:
        - "addent -password -p {{ kytab_user }} -k 1 -e rc4-hmac"
        - "{{ key_tab_pass }}"
        - "wkt /etc/krb5-2.keytab"
        - "q"

# - name: Создаю скрипт для авто монтирования шары {{ srv_name_lower }}{{ share_name_modded }}
#   ansible.builtin.template:
#     src: templates/share_script.sh
#     dest: /etc/profile.d/{{ script_name }}.sh
#     owner: root
#     group: root
#     mode: '0755'