---
- name: Устанавливаю cifs-utils
  ansible.builtin.package:
    name:
      - cifs-utils
    state: present

- name: Удаляю старый ключ
  ansible.builtin.file:
    state: absent
    path: /etc/krb5-2.keytab

- name: Копирую билет
  ansible.builtin.copy:
    src: files/ticket
    dest: /etc/krb5-2.keytab
    owner: root
    group: root
    mode: '0600'

- name: Создаю папку для скриптов
  ansible.builtin.file:
    path: /root/scripts
    state: directory
    owner: root
    group: root
    mode: '0600'

- name: Создаю папку для шары
  ansible.builtin.file:
    path: /mnt/SharedDocs/{{ dst_share_name }}
    state: directory

- name: Создаю скрипт для монтирования шары
  ansible.builtin.template:
    src: templates/mount.py
    dest: /root/scripts/{{ script_name }}.py

- name: Создаю службу для запуска скрипта монтирования шары
  ansible.builtin.template:
    src: templates/service.service
    dest: /etc/systemd/system/{{ script_name }}.service
  notify:
    - reload systemctl

- name: Запускаю службу
  service:
    name: "{{ script_name }}.service"
    state: restarted
    enabled: true

- name: Сообщение
  debug:
    msg: "{{ script_name }}"

# - name: Создаю скрипт для авто монтирования шары {{ srv_name_lower }}{{ share_name_modded }}
#   ansible.builtin.template:
#     src: templates/share_script.sh
#     dest: /etc/profile.d/{{ script_name }}.sh
#     owner: root
#     group: root
#     mode: '0755'