version: '3'
services:
  pritunl:
    container_name: pritunl
    image: bagerz2000/pritunl:latest
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - 'pritunl-data:/var/lib/pritunl'
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.20-rc0-focal
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - 'mongo-datadb:/data/db'
      - 'mongo-configdb:/data/configdb'

volumes:
  pritunl-data:
  mongo-datadb:
  mongo-configdb:
