---
- name: Astra
  ansible.builtin.import_tasks:
    file: Astra.yml
  when: ansible_facts['os_family'] == "Astra Linux" or ansible_facts['os_family'] == "Astra Linux (Orel)"

- name: Debian
  ansible.builtin.import_tasks:
    file: Debian.yml
  when: ansible_facts['os_family'] == "Debian"