- hosts: "{{ clients }}"
  become: true
  roles:
    - "../Share"
  vars:
    kytab_user: 'test-user@T8.CORP'
    key_tab_pass: 'NJI\(nhy6'
    srv_name: "DFS2.t8.corp"            # Название сервера шары, полное
    share_name: '\15_Proizvodstvo'      # Название шары, вместе со слешем

    # Промежуточные переменные. Их задавать в playbook не нужно
    srv_name_lower: "{{ srv_name | lower }}"
    share_name_modded: "{{ share_name | regex_replace('\\\\', '/')  }}"
    dst_share_name: "{{ share_name_modded | split('/') | last }}"
    script_name: "{{ srv_name_lower }}{{ share_name | regex_replace('\\\\', '-') }}"