- hosts: "{{ clients }}"
  become: true
  roles:
    - "../FreeIPA-client"
    - "../FreeIPA-sssd"
  vars:
    conn: "Проводное соединение 1"
    need_reboot_sssd: "true"
    dnsmask_install: "yes"

    