---
- name: Проверяю, существует ли пользователь
  ansible.builtin.command:
    cmd: 'id "{{ item }}"'
  loop: "{{ list_users }}"
  changed_when: false

# - name: Создаю группу для пользователя (external)
#   ansible.builtin.debug:
#     msg: "{{ item | split('@') | first }}"
#   loop: "{{ list_users }}"

- name: Создаю группу (external)
  community.general.ipa_group:
    name: "{{ item | split('@') | first }}-ext"
    external: true
    append: true
    external_user:
      - "{{ item }}"
    validate_certs: false
    ipa_user: admin
    ipa_pass: "{{ ipa_admin_pass }}"
  loop: "{{ list_users }}"

- name: Создаю группу (posix)
  community.general.ipa_group:
    name: "{{ item | split('@') | first }}"
    external: false
    append: true
    group:
      - "{{ item | split('@') | first }}-ext"
    validate_certs: false
    ipa_user: admin
    ipa_pass: "{{ ipa_admin_pass }}"
  loop: "{{ list_users }}"
  ignore_errors: true

- name: Создаю HBAC правило
  community.general.ipa_hbacrule:
    name: "{{ item | split('@') | first }}"
    servicecategory: all
    host: "{{ dst_host }}"
    state: present
    validate_certs: false
    ipa_user: admin
    ipa_pass: "{{ ipa_admin_pass }}"
  loop: "{{ list_users }}"