---
- name: Split Simple String Example
  debug:
    msg: "{{ list_users }}"

- name: Non-optimal yum, slower and may cause issues with interdependencies
  ansible.builtin.debug:
    msg: "{{ item | split('@') }}"
  loop: "{{ list_users }}"