---
- name: Split Simple String Example
  debug:
    msg: "{{ list_users }}"

- name: Проверяю, существует ли пользователь
  ansible.builtin.command:
    cmd: 'id "{{ item }}"'
  loop: "{{ list_users }}"
  changed_when: false