---
- name: Проверяю, существует ли пользователь
  ansible.builtin.command:
    cmd: 'id "{{ item }}"'
  loop: "{{ list_users }}"
  changed_when: false

- name: Создаю группу для пользователя (external)
  ansible.builtin.debug:
    msg: "{{ item }} | split('@')"