---
- name: Split Simple String Example
  debug:
    msg: "{{ list_users }}"

- name: Non-optimal yum, slower and may cause issues with interdependencies
  ansible.builtin.command:
    cmd: 'id "{{ item }}"'
  loop: "{{ list_users }}"