---
- name: Останавливаю службы
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
  loop: "{{ services }}"
  ignore_errors: true

- name: Чищу кэш
  ansible.builtin.shell:
    cmd: 'sync; echo 1 > /proc/sys/vm/drop_caches'

- name: Сбрасываю своп
  ansible.builtin.shell:
    cmd: 'swapoff -a; swapon -a'
  
- name: Запускаю службы
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
  loop: "{{ services }}"
  when: need_reboot == "no"
  ignore_errors: true

- name: Перезапускаю ПК
  ansible.builtin.reboot:
    reboot_timeout: 3600
  when: need_reboot == "yes"