- name: Меняю имя ОС
  ansible.builtin.hostname:
    name: "{{ hostname }}.ipa.t8.corp"

- name: Replace after the expression till the end of the file (requires Ansible >= 2.4)
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^(deb cdrom)'
    replace: '# \1'

- name: Добавляю репозитории main
  ansible.builtin.apt_repository:
    repo: "deb https://dl.astralinux.ru/astra/stable/1.8_x86-64/main-repository/ 1.8_x86-64 main contrib non-free"
    state: present
    filename: stable-main

- name: Добавляю репозитории extended
  ansible.builtin.apt_repository:
    repo: "deb https://dl.astralinux.ru/astra/stable/1.8_x86-64/extended-repository/ 1.8_x86-64 main contrib non-free"
    state: present
    filename: stable-extended

- name: Обновляю репозитории
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Astra Linux'

- name: Устанавливаю dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present
  when: ansible_facts['os_family'] == 'Astra Linux'

# - name: Настраиваем DNS
#   when: ansible_facts['os_family'] == 'Astra Linux'
#   block:
#     - name: Запретить использовать IP-адреса серверов DNS, предоставляемые DHCP-сервером
#       ansible.builtin.command:
#         cmd: nmcli con mod "Проводное соединение 1" ipv4.ignore-auto-dns yes
#     - name: Устанавливаем DNS IP адреса ipa серверов 
#       ansible.builtin.command:
#         cmd: nmcli con mod "Проводное соединение 1" ipv4.dns "127.0.0.1"
    