- name: Меняю имя ОС
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}.ipa.t8.corp"

- name: Комментирую репозиторий cdrom
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^(deb cdrom)'
    replace: '# \1'

- name: Добавляю репозиторий main
  ansible.builtin.apt_repository:
    repo: "{{ repo_main }}"
    state: present
    update_cache: false
    filename: stable-main

- name: Добавляю репозиторий extended
  ansible.builtin.apt_repository:
    repo: "{{ repo_extended }}"
    state: present
    update_cache: false
    filename: stable-extended

- name: Обновляю репозитории
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts['os_family'] == 'Astra Linux'

- name: Проверяю, установлен ли пакет fly-admin-freeipa-client
  ansible.builtin.apt:
    name:
      - fly-admin-freeipa-client
    state: present
  check_mode: true
  register: freeipa_client_check

- name: Удаляю конфликтующие службы
  when: freeipa_client_check.changed == "true"
  block:
    - name: Удаляю службу systemd-timesyncd
      ansible.builtin.apt:
        name: systemd-timesyncd
        state: absent
    - name: Удаляю службу chrony
      ansible.builtin.apt:
        name: chrony
        state: absent

- name: Устанавливаю dnsmasq, fly-admin-freeipa-client
  ansible.builtin.apt:
    name:
      - dnsmasq
      - astra-freeipa-client
    state: present

- name: Создаю конфиг dnsmasq
  ansible.builtin.template:
    src: templates/dnscache.conf
    dest: /etc/dnsmasq.d/dnscache.conf
    owner: root
    group: root
    mode: '0751'
  notify: restart dnsmasq

- name: Создаю резолв конфиг dnsmasq
  ansible.builtin.template:
    src: templates/resolv.dnsmasq
    dest: /etc/resolv.dnsmasq
    owner: root
    group: root
    mode: '0644'
  notify: restart dnsmasq

- name: Проверяю DNS
  ansible.builtin.shell: 'nmcli con show "{{ conn }}" | grep "IP4.DNS\[1\]"'
  register: dns_check

- name: Запрещаю использовать IP-адреса серверов DNS, предоставляемые DHCP-сервером
  ansible.builtin.command:
    cmd: nmcli con mod "{{ conn }}" ipv4.ignore-auto-dns yes

- name: Устанавливаю DNS IP адрес ipa серверов "127.0.0.1"
  ansible.builtin.command:
    cmd: nmcli con mod "{{ conn }}" ipv4.dns "127.0.0.1"
  when: '"127.0.0.1" not in dns_check.stdout'
    
- name: Перезагружаю ПК
  ansible.builtin.reboot:
  when: '"127.0.0.1" not in dns_check.stdout'

- name: Добавляем контроллеры ipa и dc в hosts
  lineinfile:
    path: "/etc/hosts"
    line: "{{ item }}"
  loop:
      - "{{ ipa1_ip }} {{ ipa1_name }}"
      - "{{ ipa2_ip }} {{ ipa2_name }}"
      - "{{ dc01_ip }} {{ dc01_name }}"
      - "{{ dc02_ip }} {{ dc02_name }}"

- name: Ввожу ПК в домен
  ansible.builtin.command:
    cmd: astra-freeipa-client -p {{ ipa_admin_pass }} -y