- name: Меняю имя ОС
  ansible.builtin.hostname:
    name: "{{ hostname }}.ipa.t8.corp"

- name: Комментирую репозиторий cdrom
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^(deb cdrom)'
    replace: '# \1'

- name: Добавляю репозиторий main
  ansible.builtin.apt_repository:
    repo: "deb https://dl.astralinux.ru/astra/stable/1.8_x86-64/main-repository/ 1.8_x86-64 main contrib non-free"
    state: present
    update_cache: false
    filename: stable-main

- name: Добавляю репозиторий extended
  ansible.builtin.apt_repository:
    repo: "deb https://dl.astralinux.ru/astra/stable/1.8_x86-64/extended-repository/ 1.8_x86-64 main contrib non-free"
    state: present
    update_cache: false
    filename: stable-extended

- name: Обновляю репозитории
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts['os_family'] == 'Astra Linux'

- name: Проверяю, установлен ли пакет fly-admin-freeipa-client
  ansible.builtin.apt:
    name:
      - fly-admin-freeipa-client
    state: present
  check_mode: true
  register: freeipa_client_check

- name: Удаляю конфликтующие службы
  when: freeipa_client_check.changed == "true"
  block:
    - name: Удаляю службу systemd-timesyncd
      ansible.builtin.apt:
        name: systemd-timesyncd
        state: absent
    - name: Удаляю службу chrony
      ansible.builtin.apt:
        name: chrony
        state: absent

- name: Устанавливаю dnsmasq, fly-admin-freeipa-client
  ansible.builtin.apt:
    name:
      - dnsmasq
      - fly-admin-freeipa-client
    state: present

- name: Создаю конфиг dnsmasq
  ansible.builtin.template:
    src: templates/dnscache.conf
    dest: /etc/dnsmasq.d/dnscache.conf
    owner: root
    group: root
    mode: '0751'
  register: dnsmasq_conf

- name: Создаю резолв конфиг dnsmasq
  ansible.builtin.template:
    src: templates/resolv.dnsmasq
    dest: /etc/resolv.dnsmasq
    owner: root
    group: root
    mode: '0644'
  register: dnsmasq_conf

- name: Перезапускаю службу dnsmasq
  service:
    name: dnsmasq
    state: restarted
  when: dnsmasq_conf.changed

- name: Проверяю DNS
  ansible.builtin.shell: 'nmcli con show "Проводное соединение 1" | grep "IP4.DNS\[1\]" | awk "{print $2}"'
  register: dns_check

- name: DNS
  ansible.builtin.debug:
    msg: "{{ dns_check }}"

- name: Запрещаю использовать IP-адреса серверов DNS, предоставляемые DHCP-сервером
  ansible.builtin.command:
    cmd: nmcli con mod "Проводное соединение 1" ipv4.ignore-auto-dns yes

- name: Устанавливаю DNS IP адрес ipa серверов "127.0.0.1"
  ansible.builtin.command:
    cmd: nmcli con mod "Проводное соединение 1" ipv4.dns "127.0.0.1"
    
# - name: Перезагружаю ПК
#   ansible.builtin.reboot: