---
- name: Run urbackup docker container
  docker_container:
    name: urbackup-server
    image: uroni/urbackup-server
    state: started
    restart_policy: unless-stopped
    published_ports:
      - 55413-55415:55413-55415
      - 35623:35623/udp
    volumes:
      - /storage/backup:/backups
      - /media/database:/var/urbackup

