---
- name: Создаю конфиг sssd.conf
  ansible.builtin.template:
    src: templates/sssd.conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: '0600'

- name: Создаю конфиг krb5.conf
  ansible.builtin.template:
    src: templates/krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'

- name: Создаю конфиг nsswitch.conf
  ansible.builtin.template:
    src: templates/nsswitch.conf
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: '0644'

- name: Останавливаем службу sssd
  ansible.builtin.service:
    name: sssd
    state: stopped

- name: Чистим кэш sssd
  ansible.builtin.command:
    cmd: rm -rf /var/lib/sss/db/*
  when: clear_sssd_cache == "y"

- name: Запускаем службу sssd
  ansible.builtin.service:
    name: sssd
    state: started