---
- name: Обновляю sssd и krb5
  block:
    - name: Создаю конфиг sssd.conf
      ansible.builtin.template:
        src: templates/sssd.conf
        dest: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: '0600'
      register: sssd_check

    - name: Создаю конфиг krb5.conf
      ansible.builtin.template:
        src: templates/krb5.conf
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: '0644'
      register: krb5_check

- name: restart sssd
  when: sssd_check.changed == true or krb5_check.changed == true
  block:
    - name: Останавливаем службу sssd
      ansible.builtin.service:
        name: sssd
        state: stopped

    - name: Чистим кэш sssd
      ansible.builtin.command:
        cmd: rm -rf /var/lib/sss/db/*

    - name: Перезапускаю ПК
      ansible.builtin.reboot:
        reboot_timeout: 3600
      when: need_reboot_sssd == true