---
- name: aaa
  command: "hostname"
  register: txt
- name: "111"
  debug:
    msg: "{{ txt.stdout }}"

- name: Удаляю хост из IPA
  community.general.ipa_host:
    name: "{{ inventory_hostname }}"
    state: absent
    validate_certs: false
    ipa_user: admin
    ipa_pass: "{{ ipa_admin_pass }}"