---
- name: Удаляю хост из IPA
  community.general.ipa_host:
    name: "{{ inventory_hostname }}"
    state: absent
    ipauserauthtype: ['password']
    ipa_user: admin
    ipa_pass: "{{ ipa_admin_pass }}"