- name: Останавливаем службу sssd
  ansible.builtin.service:
    name: sssd
    state: stopped

- name: Чистим кэш sssd
  ansible.builtin.command:
    cmd: rm -rf /var/lib/sss/db/*

- name: Запускаем службу sssd
  ansible.builtin.service:
    name: sssd
    state: started