- name: Собираю данные об установленных пакетах
  ansible.builtin.package_facts:
    manager: auto

- name: Устанавливаю graylog-sidecar
  ansible.builtin.apt:
    deb: "{{ graylog_sidecar_url }}"
  when: "'graylog-sidecar' not in ansible_facts.packages"

- name: Создаю конфиг sidecar.yml
  ansible.builtin.template:
    src: templates/sidecar.yml
    dest: /etc/graylog/sidecar/sidecar.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart sidecar

- name: Собираю данные о настроенных службах
  ansible.builtin.service_facts:

- name: Устанавливаю службу graylog-sidecar
  ansible.builtin.command: graylog-sidecar -service install
  when: 
    - "'graylog-sidecar.service' not in ansible_facts.services"

- name: Включаю и запускаю службу graylog-sidecar
  ansible.builtin.service:
    name: graylog-sidecar
    state: started
    enabled: yes