# - name: Собираем данные об установленных пакетах
#   ansible.builtin.package_facts:
#     manager: auto

# - name: Устанавливаю graylog-sidecar
#   ansible.builtin.apt:
#     deb: "{{ graylog_sidecar_url }}"
#   when: "'graylog-sidecar' not in ansible_facts.packages"

# - name: Создаю конфиг sidecar.yml
#   ansible.builtin.template:
#     src: templates/sidecar.yml
#     dest: /etc/graylog/sidecar/sidecar.yml
#     owner: root
#     group: root
#     mode: '0644'

- name: Populate service facts
  service_facts:

- debug:
    msg: graylog-sidecar installed!
  when: "'graylog-sidecar' in ansible_facts.services"