- name: Собираем данные об установленных пакетах
  ansible.builtin.package_facts:
    manager: auto

- name: Check whether a package called foobar is installed
  ansible.builtin.debug:
    msg: "{{ ansible_facts.packages['graylog-sidecar'] | length }} versions of foobar are installed!"
  when: "'graylog-sidecar' in ansible_facts.packages"

# - name: Устанавливаю graylog-sidecar
#   ansible.builtin.apt:
#     deb: "{{ graylog_sidecar_url }}"

# - name: Создаю конфиг sidecar.yml
#   ansible.builtin.template:
#     src: templates/sidecar.yml
#     dest: /etc/graylog/sidecar/sidecar.yml
#     owner: root
#     group: root
#     mode: '0644'