# - name: Скачиваю graylog-sidecar
#   ansible.builtin.get_url:
#     url: https://github.com/Graylog2/collector-sidecar/releases/download/1.5.0/graylog-sidecar_1.5.0-1_amd64.deb
#     dest: /tmp/graylog-sidecar_1.5.0-1_amd64.deb

- name: Установка клиента на Debian
  ansible.builtin.import_tasks:
    file: Debian.yml
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Astra Linux" or ansible_facts['os_family'] == "Astra Linux (Orel)"