- name: Get system facts
  hosts: "{{ hosts }}"
  become: true
  vars:
    facts: "['os_family']"
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts{{ facts }}