- name: Test Connection to Servers
  hosts: "{{  hosts  }}"
  become: true
  tasks:
    - name: Ping my Servers
      ansible.builtin.setup:
      register: system_var

    - debug:
        var: system_var