- hosts: "{{ ipa1_name }}"
  become: true
  roles:
    - "../FreeIPA-add-groups-rules"
  vars:
    # ipa1_name: ipa1.ipa.example.com   # Название IPA сервера в инвентори
    # ipa_admin_pass: superpass         # Пароль от учетной записи администратора
    # nm: "{{ 'sarav@gritfy.com'|split('@') }}"
    list_users: ['polyakov.rv@t8.corp', 'polyakov.rv2@t8.corp']